package frc.robot.commands.armwristcommands;

public enum ArmPositionValues {
    LOWROCKETSHOULDERANGLEFORCARGO(-10.73), 
    LOWROCKETSHOULDERANGLEFORHATCH(-4.0), 
    MIDDLEROCKETSHOULDERANGLEFORCARGO(175.52), 
    MIDDLEROCKETSHOULDERANGLEFORHATCH(147), 
    CARGOSHIPSHOULDERANGLE(151), 
    CARGOLOADINGSTATIONSHOULDERANGLE(11.75), 
    HIGHROCKETSHOULDERANGLEFORCARGO(126.16), 
    HIGHROCKETSHOULDERANGLEFORHATCH(126.16),

    LOWROCKETWRISTANGLEFORCARGO(91.12), 
    LOWROCKETWRISTANGLEFORHATCH(95.5), 
    MIDDLEROCKETWRISTANGLEFORCARGO(-82.95), 
    MIDDLEROCKETWRISTANGLEFORHATCH(-57), 
    CARGOSHIPWRISTANGLE(-98.59), 
    CARGOLOADINGSTATIONWRISTANGLE(122.11), 
    HIGHROCKETWRISTANGLEFORCARGO(-56.58), 
    HIGHROCKETWRISTANGLEFORHATCH(-89.39),

    LOWROCKETEXTENSIONFORCARGO(25.6), 
    LOWROCKETEXTENSIONFORHATCH(11.88), 
    MIDDLEROCKETEXTENSIONFORCARGO(18.9), 
    MIDDLEROCKETEXTENSIONFORHATCH(25.234), 
    CARGOSHIPEXTENSION(20.92), 
    CARGOLOADINGSTATIONEXTENSION(26.75), 
    HIGHROCKETEXTENSIONFORCARGO(0), 
    HIGHROCKETEXTENSIONFORHATCH(0),

    WRISTSTOWEDFORROTATINGDEGREES(100),
    EXTENSIONSTOWEDFORROTATINGINCHES(22),
    EXTENSIONSTOWEDHIGHFORROTATINGINCHES(27.5);


    private double value;
    private ArmPositionValues(double valueParam) {
        value = valueParam;
    }

    public double get() {
        return value;
    }
}