package frc.robot.commands.armwristcommands;

public enum ArmPositionValues {
    LOWROCKETSHOULDERANGLEFORCARGO(-10.73), 
    LOWROCKETWRISTANGLEFORCARGO(91.12), 
    LOWROCKETEXTENSIONFORCARGO(25.6),

    LOWROCKETSHOULDERANGLEFORHATCH(-4.0), 
    LOWROCKETWRISTANGLEFORHATCH(95.5),
    LOWROCKETEXTENSIONFORHATCH(11.88), 

    MIDDLEROCKETSHOULDERANGLEFORCARGO(175.52), 
    MIDDLEROCKETWRISTANGLEFORCARGO(-82.95), 
    MIDDLEROCKETEXTENSIONFORCARGO(18.9), 

    MIDDLEROCKETSHOULDERANGLEFORHATCH(147),
    MIDDLEROCKETWRISTANGLEFORHATCH(-57), 
    MIDDLEROCKETEXTENSIONFORHATCH(25.234),

    CARGOSHIPSHOULDERANGLE(151), 
    CARGOSHIPWRISTANGLE(-98.59),
    CARGOSHIPEXTENSION(20.92), 

    CARGOLOADINGSTATIONSHOULDERANGLE(11.75), 
    CARGOLOADINGSTATIONWRISTANGLE(122.11),
    CARGOLOADINGSTATIONEXTENSION(26.75),

    HIGHROCKETSHOULDERANGLEFORCARGO(126.16),
    HIGHROCKETWRISTANGLEFORCARGO(-56.58),
    HIGHROCKETEXTENSIONFORCARGO(0), 

    HIGHROCKETSHOULDERANGLEFORHATCH(126.16),
    HIGHROCKETWRISTANGLEFORHATCH(-89.39), 
    HIGHROCKETEXTENSIONFORHATCH(0),

    WRISTSTOWEDFORROTATINGDEGREES(100),
    EXTENSIONSTOWEDFORROTATINGINCHES(22),
    EXTENSIONSTOWEDHIGHFORROTATINGINCHES(27.5);


    private double value;
    private ArmPositionValues(double valueParam) {
        value = valueParam;
    }

    public double get() {
        return value;
    }
}