package frc.robot.groupcommands.armwristcommands;

public enum ArmPositions {
    LOWROCKETGAMEPIECE, CARGOLOADINGSTATIONANDCARGOSHIP, MIDDLEROCKETGAMEPIECE, HIGHROCKETGAMEPIECE, STOWEDFORROTATINGARM
}